version: '3.7'

services:
  fastapi:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    restart: always
    tty: true
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=secret
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    platform: linux/amd64

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
    platform: linux/amd64
  tool:
    image: rediscommander/redis-commander:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=localhost:redis:6379
    ports:
      - "8002:8081"
    platform: linux/amd64
